name: horizontal_card_pager
description: Use dynamic and beautiful card view pagers (horizontal direction) to help you create great apps.
version: 1.1.1
homepage: https://github.com/Origogi/Horizontal_Card_Pager

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  vimeo_player_flutter: ^0.0.3+2
  vimeo_video_player: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter